# fly.toml app configuration file generated for networth-calc on 2023-08-23T21:55:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "networth-calc"
primary_region = "sea"

[build]
  image="alinisarahmed/net-worth-calc:latest"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
